name: On push

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - data/*.ttl
      - .ogc/*

jobs:
  uplift:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ogc-na
      - name: Process files
        env:
          DB_USERNAME: admin
          DB_PASSWORD: ${{ secrets.UPLOAD_GRAPH_STORE_PASSWORD }}
        run: |
          # Uplift is disabled
          # python -m ogc.na.ingest_json --batch -t --work-dir . -d .ogc/catalog.ttl --all
          # Validate, entail and upload
          python -m ogc.na.update_vocabs -w . .ogc/catalog.ttl \
            --base-uri https://raw.githubusercontent.com/${{github.repository}}/${{github.ref_name}} \
            --update --graph-store http://defs-dev.opengis.net/fuseki-ksa/data \
            --batch
